-- WARNING: Do NOT edit the input and output ports in this file in a text
-- editor if you plan to continue editing the block that represents it in
-- the Block Editor! File corruption is VERY likely to occur.

-- Copyright (C) 1991-2009 Altera Corporation
-- Your use of Altera Corporation's design tools, logic functions 
-- and other software and tools, and its AMPP partner logic 
-- functions, and any output files from any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Altera Program License 
-- Subscription Agreement, Altera MegaCore Function License 
-- Agreement, or other applicable license agreement, including, 
-- without limitation, that your use is for the sole purpose of 
-- programming logic devices manufactured by Altera and sold by 
-- Altera or its authorized distributors.  Please refer to the 
-- applicable agreement for further details.


-- Generated by Quartus II Version 9.0 (Build Build 132 02/25/2009)
-- Created on Tue Oct 17 15:43:21 2023

LIBRARY ieee;
USE ieee.std_logic_1164.all;


--  Entity Declaration

ENTITY addr_decoder IS
	-- {{ALTERA_IO_BEGIN}} DO NOT REMOVE THIS LINE!
	PORT
	(
		nECS : IN STD_LOGIC;
		nOCS : IN STD_LOGIC;
		nAS : IN STD_LOGIC;
		A : IN STD_LOGIC_VECTOR(31 downto 0);
		nCIIN : IN STD_LOGIC;
		FC : IN STD_LOGIC_VECTOR(2 downto 0);
		nCIOUT : OUT STD_LOGIC;
		nDRAM_SEL : OUT STD_LOGIC;
		nCPCS : OUT STD_LOGIC;
		nFMCS : OUT STD_LOGIC
	);
	-- {{ALTERA_IO_END}} DO NOT REMOVE THIS LINE!
	
END addr_decoder;


--  Architecture Body

ARCHITECTURE addr_decoder_architecture OF addr_decoder IS

	
BEGIN
	nFMCS <= '0' WHEN (
		(nECS = '0' OR nOCS = '0') AND
		FC /= "111" AND
		A(31 DOWNTO 20) = x"000") ELSE '1';
		
	nCPCS <= '0' WHEN (
		(nECS = '0' OR nOCS = '0') AND
		FC = "111" AND
		A(19 DOWNTO 13) = x"0001001") ELSE '1';
		
	nDRAM_SEL <= '0' WHEN (
		(nECS = '0' OR nOCS = '0') AND
		FC /= "111" AND
		A(31 downto 20) /= x"000" AND
		A(31 downto 20) /= x"FFF") ELSE '1';
		
	nCIOUT <= '0' WHEN (
		nCIIN = '0' OR
		FC = "111" OR
		A(31 downto 20) = x"FFF") ELSE '1';
END addr_decoder_architecture;
