-- WARNING: Do NOT edit the input and output ports in this file in a text
-- editor if you plan to continue editing the block that represents it in
-- the Block Editor! File corruption is VERY likely to occur.

-- Copyright (C) 1991-2009 Altera Corporation
-- Your use of Altera Corporation's design tools, logic functions 
-- and other software and tools, and its AMPP partner logic 
-- functions, and any output files from any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Altera Program License 
-- Subscription Agreement, Altera MegaCore Function License 
-- Agreement, or other applicable license agreement, including, 
-- without limitation, that your use is for the sole purpose of 
-- programming logic devices manufactured by Altera and sold by 
-- Altera or its authorized distributors.  Please refer to the 
-- applicable agreement for further details.


-- Generated by Quartus II Version 9.0 (Build Build 132 02/25/2009)
-- Created on Sat Oct 21 22:36:02 2023

LIBRARY ieee;
USE ieee.std_logic_1164.all;


--  Entity Declaration

ENTITY badec IS
	-- {{ALTERA_IO_BEGIN}} DO NOT REMOVE THIS LINE!
	PORT
	(
		BA : IN STD_LOGIC_VECTOR(2 downto 0);
		nOE : IN STD_LOGIC;
		nRAS : OUT STD_LOGIC_VECTOR(7 downto 0)
	);
	-- {{ALTERA_IO_END}} DO NOT REMOVE THIS LINE!
	
END badec;


--  Architecture Body

ARCHITECTURE badec_architecture OF badec IS

	
BEGIN
	WITH (BA(2 downto 0) & nOE) SELECT
		nRAS <= "11111110" WHEN "0000",
		        "11111011" WHEN "0010",
		        "11101111" WHEN "0100",
		        "10111111" WHEN "0110",
		        "11111101" WHEN "1000",
		        "11110111" WHEN "1010",
		        "11011111" WHEN "1100",
		        "01111111" WHEN "1110",
		        "11111111" WHEN OTHERS;
END badec_architecture;
