-- WARNING: Do NOT edit the input and output ports in this file in a text
-- editor if you plan to continue editing the block that represents it in
-- the Block Editor! File corruption is VERY likely to occur.

-- Copyright (C) 1991-2009 Altera Corporation
-- Your use of Altera Corporation's design tools, logic functions 
-- and other software and tools, and its AMPP partner logic 
-- functions, and any output files from any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Altera Program License 
-- Subscription Agreement, Altera MegaCore Function License 
-- Agreement, or other applicable license agreement, including, 
-- without limitation, that your use is for the sole purpose of 
-- programming logic devices manufactured by Altera and sold by 
-- Altera or its authorized distributors.  Please refer to the 
-- applicable agreement for further details.


-- Generated by Quartus II Version 9.0 (Build Build 132 02/25/2009)
-- Created on Sun Oct 22 12:23:31 2023

LIBRARY ieee;
USE ieee.std_logic_1164.all;


--  Entity Declaration

ENTITY cache_controller IS
	-- {{ALTERA_IO_BEGIN}} DO NOT REMOVE THIS LINE!
	PORT
	(
		A : IN STD_LOGIC_VECTOR(31 downto 2);
		nEN : IN STD_LOGIC;
		nCDV : OUT STD_LOGIC;
		nCOE : OUT STD_LOGIC;
		nCWE : OUT STD_LOGIC;
		CA : OUT STD_LOGIC_VECTOR(19 downto 0);
		TD : INOUT STD_LOGIC_VECTOR(15 downto 0)
	);
	-- {{ALTERA_IO_END}} DO NOT REMOVE THIS LINE!
	
END cache_controller;


--  Architecture Body

ARCHITECTURE cache_controller_architecture OF cache_controller IS

	
BEGIN
	nCDV <= '1';
END cache_controller_architecture;
