-- WARNING: Do NOT edit the input and output ports in this file in a text
-- editor if you plan to continue editing the block that represents it in
-- the Block Editor! File corruption is VERY likely to occur.

-- Copyright (C) 1991-2009 Altera Corporation
-- Your use of Altera Corporation's design tools, logic functions 
-- and other software and tools, and its AMPP partner logic 
-- functions, and any output files from any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Altera Program License 
-- Subscription Agreement, Altera MegaCore Function License 
-- Agreement, or other applicable license agreement, including, 
-- without limitation, that your use is for the sole purpose of 
-- programming logic devices manufactured by Altera and sold by 
-- Altera or its authorized distributors.  Please refer to the 
-- applicable agreement for further details.


-- Generated by Quartus II Version 9.0 (Build Build 132 02/25/2009)
-- Created on Sun Oct 22 12:23:50 2023

LIBRARY ieee;
USE ieee.std_logic_1164.all;


--  Entity Declaration

ENTITY cpu_if IS
	-- {{ALTERA_IO_BEGIN}} DO NOT REMOVE THIS LINE!
	PORT
	(
		nRST : IN STD_LOGIC;
		nREG_SEL : IN STD_LOGIC;
		nDRAM_EN : IN STD_LOGIC;
		DBMM : OUT STD_LOGIC;
		BSIZ : OUT STD_LOGIC_VECTOR(2 downto 0);
		MCNT : OUT STD_LOGIC_VECTOR(1 downto 0);
		IVL : OUT STD_LOGIC_VECTOR(19 downto 0);
		nCEN : OUT STD_LOGIC;
		nFEN : OUT STD_LOGIC;
		D : INOUT STD_LOGIC
	);
	-- {{ALTERA_IO_END}} DO NOT REMOVE THIS LINE!
	
END cpu_if;


--  Architecture Body

ARCHITECTURE cpu_if_architecture OF cpu_if IS

	
BEGIN

END cpu_if_architecture;
