-- WARNING: Do NOT edit the input and output ports in this file in a text
-- editor if you plan to continue editing the block that represents it in
-- the Block Editor! File corruption is VERY likely to occur.

-- Copyright (C) 1991-2009 Altera Corporation
-- Your use of Altera Corporation's design tools, logic functions 
-- and other software and tools, and its AMPP partner logic 
-- functions, and any output files from any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Altera Program License 
-- Subscription Agreement, Altera MegaCore Function License 
-- Agreement, or other applicable license agreement, including, 
-- without limitation, that your use is for the sole purpose of 
-- programming logic devices manufactured by Altera and sold by 
-- Altera or its authorized distributors.  Please refer to the 
-- applicable agreement for further details.


-- Generated by Quartus II Version 9.0 (Build Build 132 02/25/2009)
-- Created on Tue Oct 17 14:42:52 2023

LIBRARY ieee;
USE ieee.std_logic_1164.all;


--  Entity Declaration

ENTITY dram_amux IS
	-- {{ALTERA_IO_BEGIN}} DO NOT REMOVE THIS LINE!
	PORT
	(
		MUXSEL : IN STD_LOGIC_VECTOR(1 downto 0);
		A : IN STD_LOGIC_VECTOR(31 downto 2);
		DBMM : IN STD_LOGIC;
		BSIZ : IN STD_LOGIC_VECTOR(2 downto 0);
		MCNT : OUT STD_LOGIC_VECTOR(1 downto 0);
		RA : OUT STD_LOGIC_VECTOR(11 downto 0);
		CA : OUT STD_LOGIC_VECTOR(11 downto 0);
		BA : OUT STD_LOGIC_VECTOR(2 downto 0)
	);
	-- {{ALTERA_IO_END}} DO NOT REMOVE THIS LINE!
	
END dram_amux;


--  Architecture Body

ARCHITECTURE dram_amux_architecture OF dram_amux IS


BEGIN
	WITH (MUXSEL) SELECT
		CA <= (A(24) & A(22) & A(20) & A(10 DOWNTO 2))
		          WHEN "00",                                -- MUX Type 1, CAS
		      (A(24) & A(23) & A(11) & A(10 DOWNTO 2))
		          WHEN "01",                                -- MUX Type 2, CAS
		      (A(25 DOWNTO 22) & A(9 DOWNTO 2))
		          WHEN "10",                                -- MUX Type 3, CAS
		      (A(13 DOWNTO 2))
		          WHEN "11",                                -- MUX TEST,   CAS
	          "ZZZZZZZZZZZZ"                                        WHEN OTHERS;

	WITH (MUXSEL) SELECT
		RA <= (A(25) & A(23) & A(21) & A(19 DOWNTO 11))
		          WHEN "00",                                -- MUX Type 1, RAS
		      (A(11) & A(22) & A(21) & A(20 DOWNTO 12))
		          WHEN "01",                                -- MUX Type 2, RAS
		      (A(11) & A(10) & A(21 DOWNTO 12))
		          WHEN "10",                                -- MUX Type 2, RAS
		      (A(25 DOWNTO 14))
		          WHEN "11",                                -- MUX TEST,   RAS
	          "ZZZZZZZZZZZZ"                                        WHEN OTHERS;
	          
	WITH (BSIZ) SELECT
		BA <= A(20 DOWNTO 18)                                 WHEN "000",
		                                                      -- 256kiB  Bank(s)
		      A(21 DOWNTO 19)                                 WHEN "001",
		                                                      -- 512kiB  Bank(s)
		      A(22 DOWNTO 20)                                 WHEN "010",
		                                                      -- 1MiB    Bank(s)
		      A(23 DOWNTO 21)                                 WHEN "011",
		                                                      -- 2MiB    Bank(s)
		      A(24 DOWNTO 22)                                 WHEN "100",
		                                                      -- 4MiB    Bank(s)
		      A(25 DOWNTO 23)                                 WHEN "101",
		                                                      -- 8MiB    Bank(s)
		      A(26 DOWNTO 24)                                 WHEN "110",
		                                                      -- 16MiB   Bank(s)
		      "000"                                           WHEN OTHERS;
	
END dram_amux_architecture;
