-- WARNING: Do NOT edit the input and output ports in this file in a text
-- editor if you plan to continue editing the block that represents it in
-- the Block Editor! File corruption is VERY likely to occur.

-- Copyright (C) 1991-2009 Altera Corporation
-- Your use of Altera Corporation's design tools, logic functions 
-- and other software and tools, and its AMPP partner logic 
-- functions, and any output files from any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Altera Program License 
-- Subscription Agreement, Altera MegaCore Function License 
-- Agreement, or other applicable license agreement, including, 
-- without limitation, that your use is for the sole purpose of 
-- programming logic devices manufactured by Altera and sold by 
-- Altera or its authorized distributors.  Please refer to the 
-- applicable agreement for further details.


-- Generated by Quartus II Version 9.0 (Build Build 132 02/25/2009)
-- Created on Sat Oct 21 15:25:17 2023

LIBRARY ieee;
USE ieee.std_logic_1164.all;


--  Entity Declaration

ENTITY dram_controller IS
	-- {{ALTERA_IO_BEGIN}} DO NOT REMOVE THIS LINE!
	PORT
	(
		nREFRESH : IN STD_LOGIC;
		R_nW : IN STD_LOGIC;
		nDRAM_SEL : IN STD_LOGIC;
		RAS_nCAS : OUT STD_LOGIC;
		nMWE : OUT STD_LOGIC;
		nMOE : OUT STD_LOGIC;
		nMDV : OUT STD_LOGIC;
		nRASEN : OUT STD_LOGIC;
		nCAS : OUT STD_LOGIC_VECTOR(3 downto 0);
		nAOE : OUT STD_LOGIC
	);
	-- {{ALTERA_IO_END}} DO NOT REMOVE THIS LINE!
	
END dram_controller;


--  Architecture Body

ARCHITECTURE dram_controller_architecture OF dram_controller IS

	
BEGIN
	nMOE <= '0';
	nRASEN <= '0';
	RAS_nCAS <= '1';
	nMDV <= '1';
	nCAS <= x"F";
END dram_controller_architecture;
